# syntax=docker/dockerfile:1.4.1
FROM debian:bookworm-slim@sha256:804194b909ef23fb995d9412c9378fb3505fe2427b70f3cc425339e48a828fca

# enable snapshot
RUN <<'_EOFEOF_' bash

set -eu
set -o posix
set -o pipefail

cd /etc/apt/sources.list.d/
perl -pe 's|^URIs: http://.+\n||g' < debian.sources | perl -pe 's|^#(?= http://snapshot.debian.org/)|URIs:|g' > debian.sources-new
mv debian.sources-new debian.sources

_EOFEOF_

RUN apt-get -o Acquire::Check-Valid-Until=false update

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --download-only -y build-essential devscripts debhelper
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y build-essential devscripts debhelper
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --download-only -y nodejs npm
RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y nodejs npm

COPY --chmod=644 files/ /work/resources/files/
COPY debian/ /work/resources/debian/
COPY create-changelog/ /create-changelog/
COPY changelog.yaml /

RUN cd /create-changelog && npm install && node create-changelog.js < /changelog.yaml > /work/resources/debian/changelog

RUN cd /work/resources && debuild -us -uc

RUN mkdir /results && mv /work/tksst-zsh-config_* /results/
