# syntax=docker/dockerfile:1.2.1
FROM public.ecr.aws/debian/debian:bullseye-20221024-slim

RUN mkdir -p /work/opt/tksst/zsh/ /work/DEBIAN /results

COPY --chmod=644 files/ /work/opt/tksst/zsh
COPY control /work/DEBIAN/

RUN dpkg-deb --build /work /results/
