name: Build
on:
  push:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  TAG: tmp:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Build the container
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile_deb-builder
          load: true
          tags: ${{ env.TAG }}

      - name: Extracting artifacts from containers
        run: docker run -v "${PWD}/work/:/mnt" ${{ env.TAG }} sh -c 'cp -a /results/ /mnt/'

      - name: Upload artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: deb-packages
          path: |
            ./work/results/*.deb
            ./work/results/*.dsc
            ./work/results/*.tar.*
