name: Build
on:
  push:
  pull_request:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

env:
  TAG: tmp:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Checkout repository (Base Branch)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.base_ref }}

      - name: Build the container (Base Branch)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile_deb-builder
          load: true
          tags: ${{ env.TAG }}

      - name: Print artifacts' checksums (Base Branch)
        if: github.event_name == 'pull_request'
        run: docker run ${{ env.TAG }} sh -c 'sha256sum /artifacts/*' | tee /tmp/base.txt

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Build the container
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile_deb-builder
          load: true
          tags: ${{ env.TAG }}

      - name: Print artifacts' checksums
        run: docker run ${{ env.TAG }} sh -c 'sha256sum /artifacts/*' | tee /tmp/ref.txt

      - name: Extracting artifacts from containers
        run: docker run -v "${PWD}/work/:/mnt" ${{ env.TAG }} sh -c 'cp -a /artifacts/ /mnt/'

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: deb-packages
          path: ./work/artifacts/

      - name: Comment to the PR
        if: github.event_name == 'pull_request'
        env:
          pr_number: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
        shell: bash --noprofile --norc -eu -o pipefail -o posix {0}
        run: |
          mv /tmp/ref.txt /tmp/merged.txt

          ( ( cd /tmp && diff --unified=99999 base.txt merged.txt ) || true ) > /tmp/diff.txt

          if [[ -s /tmp/diff.txt ]]; then
            echo "The artifacts have changed between merging this PR:"
            echo '```diff'
            cat /tmp/diff.txt
            echo '```'
          else
            echo "The artifacts remains unchanged between merging this PR:"
            echo '```'
            cat /tmp/merged.txt
            echo '```'
          fi | gh pr comment "$pr_number" -F -
