name: Build and Release

on:
  push:

env:
  TAG: tmp:latest

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # using .git directory in the container build, so checkout the repo and use the path context

      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Build
        uses: docker/build-push-action@f6010ea70151369b06f0194be1051fbbdff851b2 # v6.0.2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile_deb-builder
          load: true
          tags: ${{ env.TAG }}

      - name: 
        run: docker run -v "${PWD}/work/:/mnt" ${{ env.TAG }} sh -c 'cp -a /results/ /mnt/'

      - name: Upload artifact
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: deb-packages
          path: ./work/results/*.deb

      - name: Release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2.0.5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ./work/results/*.deb
