name: Build and Release

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -eu -o pipefail -o posix {0}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    outputs:
      commit-sha: ${{ steps.metadata.outputs.commit-sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: ./release-scripts/.nvmrc

      - name: Set the time in the changelog to the current time
        run: |
          cd release-scripts
          npm ci
          node update-the-date.js < ../changelog.yaml > ../changelog.yaml.new
          mv ../changelog.yaml.new ../changelog.yaml

      - name: Commit the changelog
        run: |
          git config --global user.email action@github.com
          git config --global user.name actions-user
          git add -A
          git commit -m "[skip ci] set the current time in the changelog"
          git push

      - name: output the current commit SHA
        id: metadata
        run: echo "commit-sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"

  build:
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ needs.prepare.outputs.commit-sha }}
    needs: prepare
    permissions:
      contents: write

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs:
      - prepare
      - build
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ needs.prepare.outputs.commit-sha }}

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: ./release-scripts/.nvmrc

      - name: Install dependencies
        run: cd release-scripts && npm ci

      - name: extract the new version from the changelog
        id: metadata
        run: echo "version=$( node ./release-scripts/newest-version.js < changelog.yaml )" | tee -a "$GITHUB_OUTPUT"

      - name: Generate a release note body
        run: node ./release-scripts/create-release-body.js < changelog.yaml | tee release-note-body.md

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: deb-packages
          path: ./artifacts/

      - name: Release
        uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
        with:
          files: ./artifacts/*
          body_path: release-note-body.md
          target_commitish: ${{ needs.prepare.outputs.commit-sha }}
          tag_name: v${{ steps.metadata.outputs.version }}
